---
- hosts: web
  remote_user: george
  tasks:
    - name: Pull new image
      shell: docker pull registry.jorgeadolfo.com/my-app:latest

    - name: Stop my-app
      shell: cd /var/docker/my-app && docker-compose stop && docker-compose rm -f
      ignore_errors: yes

    - name: Start my-app
      shell: cd /var/docker/my-app && docker-compose up -d
      ignore_errors: yes